// generated by docs

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:uuid/uuid.dart';

class Reminder {
  final String rid;
  final String pid;
  final String title;
  final bool isDone;

  const Reminder({
    required this.rid,
    required this.pid,
    required this.title,
    required this.isDone,
  });

  static Reminder fromJson(Map json, String pid) {
    return Reminder(
      rid: const Uuid().v1(),
      pid: pid,
      title: json["title"],
      isDone: false,
    );
  }

  static Reminder fromSnap(DocumentSnapshot snap) {
    var snapshot = snap.data() as Map<String, dynamic>;
    return Reminder(
      rid: snapshot["rid"],
      pid: snapshot["pid"],
      title: snapshot["title"],
      isDone: snapshot["isDone"],
    );
  }

  Map<String, dynamic> toJson() => {
        "rid": rid,
        "pid": pid,
        "title": title,
        "isDone": isDone,
      };
}
